name: Run Tests
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: |
          sudo apt-get install sox libfst-dev libngram-dev ninja-build \
               libopenblas-dev python3-numpy python3-scipy
      - name: Build
        run: |
          cmake -S . -B build -G Ninja -DBUILD_G2P=ON -DBUILD_SHARED_LIBS=ON
          cmake --build build
      - name: Run tests
        run: |
          cmake --build build --target test
      - name: Checkout PocketSphinx
        uses: actions/checkout@v3
        with:
          repository: cmusphinx/pocketsphinx
          path: pocketsphinx
      - name: Checkout AN4
        uses: actions/checkout@v3
        with:
          repository: cmusphinx/an4
          path: an4
      - name: Build PocketSphinx
        run: |
          cmake -S pocketsphinx -B pocketsphinx/build -G Ninja
          cmake --build pocketsphinx/build
          cp pocketsphinx/build/pocketsphinx_batch build/
      - name: Train AN4 (basic)
        run: |
          cd an4
          python ../scripts/sphinxtrain -t an4 setup
          python ../scripts/sphinxtrain run
      - name: Train AN4 (all)
        run: |
          cd an4
          git clean -df
          git checkout etc
          python ../scripts/sphinxtrain -t an4 setup
          perl -i -pe 's/((?:G2P|FORCEDALIGN|LDA|FALIGN).*)no/${1}yes/g' etc/sphinx_train.cfg
          python ../scripts/sphinxtrain run
      - name: Train AN4 (installed)
        run: |
          cmake --build build install
          cmake --build pocketsphinx/build install
          /sbin/ldconfig
          cd an4
          git clean -df
          git checkout etc
          sphinxtrain -t an4 setup
          sphinxtrain run
      - name: Train AN4 (parallel)
        run: |
          cd an4
          git clean -df
          git checkout etc
          perl -i -pe 's/(NPART.*)1/${1}4/g' etc/sphinx_train.cfg
          perl -i -pe 's/(QUEUE_TYPE.*Queue)/${1}::POSIX/g' etc/sphinx_train.cfg
          sphinxtrain -t an4 setup
          sphinxtrain run
