name: Run Tests
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: sphinxbase
      - name: Install
        run: |
          sudo apt-get install libfst-dev libngram-dev cmake \
               ninja-build libopenblas-dev python3-numpy python3-scipy
      - name: Build
        run: |
          cmake -S sphinxbase -B sphinxbase/build -G Ninja -DBUILD_G2P=ON
          cmake --build sphinxbase/build
      - name: Run tests
        run: |
          cmake --build sphinxbase/build --target test
      - name: Checkout PocketSphinx
        uses: actions/checkout@v3
        with:
          repository: cmusphinx/pocketsphinx
          path: pocketsphinx
      - name: Build PocketSphinx
        run: |
          cmake -S pocketsphinx -B pocketsphinx/build -G Ninja
          cmake --build pocketsphinx/build
          cp pocketsphinx/build/pocketsphinx_batch build/
      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            sphinxbase
            pocketsphinx
            !sphinxbase/.git
            !pocketsphinx/.git

  train-inplace:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download build
        id: download
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Install
        run: |
          sudo apt-get install libfst-dev libngram-dev cmake \
               ninja-build libopenblas-dev python3-numpy python3-scipy
      - name: Checkout AN4
        uses: actions/checkout@v3
        with:
          repository: cmusphinx/an4
          path: an4
      - name: Train AN4 (inplace)
        run: |
          cd an4
          ls ../sphinxbasescripts
          ls ../sphinxbase/build
          python3 ../sphinxbase/scripts/sphinxtrain -t an4 setup
          python3 ../sphinxbase/scripts/sphinxtrain run
      - name: Archive AN4 logs
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: an4-logdir
          path: an4/logdir

  train-installed:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download build
        id: download
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Install
        run: |
          sudo apt-get install libfst-dev libngram-dev cmake \
               ninja-build libopenblas-dev python3-numpy python3-scipy
          sudo cmake --build sphinxbase/build --target install
          sudo cmake --build pocketsphinx/build --target install
      - name: Checkout AN4
        uses: actions/checkout@v3
        with:
          repository: cmusphinx/an4
          path: an4
      - name: Train AN4 (installed)
        run: |
          cd an4
          sphinxtrain -t an4 setup
          sphinxtrain run
      - name: Archive AN4 logs
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: an4-logdir
          path: an4/logdir
